#+title: 2925-10-92

* How are you feeling right now?
I feeling extremely drain right now, I lost the battle and I give all in to Allah, the power, the status and the advantage I had on my siblings. I cried yesterday a lot in Tahajjud or before sleeping. My veins are giving electric sensations when I cried heavyly, I lost all hope in myself becoming the person I want to be become and I just give all the Allah, my hearts gives burning sensations, boiling tears were streaming down slowly. Then upon waking up after sleeping, the tears were still their, my heart feels left out and betrayed.
* What are the things you value deeply?
I value having strong and meaningful relationship with Allah, becaues it keeps my heart alive, pure, and free from distration. I love having imtimate relationship with Allah. I also value being submissive, innocent, naive, shy, pure, loving, caring, and posessive. But I can be like that because I deeply fear being taken as advantage, people might critisize me or might see it as wried.
** How can I become the person I want to?
I can start by connecting emotions to my body, then I can fantesize about the person I want to become, and consistently journaling on my emotions, well-being, spirituality, and more.
