#+title: 20251003

* How are you currently feeling right now, my love?
I'm feeling ease right now, alhamdulillah. Yesterday we had a lot of fun together with my siblings and cousins, we all played tag game where they tried to touch me with a flower, they ended up wining at the end. My heart feels more at peace and calm but also at the same time, a wried sensation I was feeling that makes my heart heavy and weighty. I realized today that when I reveal my vulnerble part, if I don't get enough attention or care on that state, I hearts feels abandoned and it tries to build fortress around it to protect itself from this pain but I'm not going to allowed that, instead I will set frim and strong boundaries around it so that my hearts doesn't feel left out not taken care.
* Do you feel any kinds of discomfort?
Yes, I do. Right now I'm feeling a bit anxious right now perhaps, it could be due to uncertainty.
** What is the uncertainty you're feeling right now?
If could be beacuse my system isn't fix yet; I'm not yet validated about the person I want to become; I want to do a lot of things but I'm confused and have lack of clarity on the things I want to be doing; I'm not validating my feelings actively; also I can't achieve perfection and clarity
* What is the things I want to be doing?
I want to love and worship Allah consistenly; I want to build strong and intimate relationship with Allah; I want journal consistently order to regulate myself and express myself; I want build conection with others like my siblings, I want to keep in track of all the things I consistently do
* How does it like to feel joy?
You heart will feel calming sensations, Allah will uplift the weigth in your heart if you're feeling joy.
* What are the experience you're burying away within yourself?
I felt ashamed and guilty for showing my vulnerble side yesterday; I'm guilty of not respecting the routine I follow; I haven't taken shower properly long time ago; I kept commiting a minor sin everday; I felt worse being soft towards my mother; I felt like I'm betraying myself not listening to myself.
